#!/data/data/com.termux/files/usr/bin/zsh

#variables
target=$(termux-clipboard-get)

#colors
DG='\e[1;30m' # dark grey
LR='\e[1;31m' # light red
LG='\e[1;32m' # light green
LY='\e[1;33m' # light yellow
LB='\e[1;34m' # light blue
W='\e[1;37m'  # white
R='\e[0m'     # reset color / no color

echo "${DG}Analysing URL..."
echo "[${LB}$target${DG}]"
echo ""
echo "${LG}What should i do?"
echo ""
echo "${LY}v${W}) Download video"
echo "${LY}s${W}) Download video (Select format)"
echo "${LY}m${W}) Download music"
echo "${LY}i${W}) Download image"
echo "${LY}w${W}) Download with wget"
echo "${LY}a${W}) Download with aria2"
echo "${LY}n${W}) Download with megatools"
echo "${LY}g${W}) Clone git"
echo "${LY}p${W}) Clone website"
echo "${LY}x${W}) ${LR}Exit${R}"

read CHOICE
case $CHOICE in
v)
  yt-dlp -n -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b" --embed-thumbnail --no-mtime -o "/storage/emulated/0/Movies/%(title)s.%(ext)s" $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finished
    echo "${LG}Done.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Error
    echo "${LR}Error.${R}"
    echo ""
    echo "${W}Press any key to exit...${R}"
    read -k 1 -r -s
  fi
  ;;
s)
  yt-dlp -F $target
  echo "${LG}Select the format:${R}"
  read FORMAT
  yt-dlp -n -f $FORMAT --embed-thumbnail --no-mtime -o "/storage/emulated/0/Movies/%(title)s.%(ext)s" $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finished
    echo "${LG}Done.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Error
    echo "${LR}Error.${R}"
    echo ""
    echo "${W}Press any key to exit...${R}"
    read -k 1 -r -s
  fi
  ;;
m)
  yt-dlp -n -x --audio-format mp3 --audio-quality 0 --embed-thumbnail --convert-thumbnail jpg --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" --exec ffprobe --add-metadata --no-mtime -o "/storage/emulated/0/Music/%(artist,uploader)s - %(title)s.%(ext)s" $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finished
    echo "${LG}Done.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Error
    echo "${LR}Error.${R}"
    echo ""
    echo "${W}Press any key to exit...${R}"
    read -k 1 -r -s
  fi
  ;;
i)
  gallery-dl --netrc --no-mtime -f '{filename}.{extension}' -d "/storage/emulated/0/Pictures/Gallery dl" $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finished
    echo "${LG}Done.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Error
    echo "${LR}Error.${R}"
    echo ""
    echo "${W}Press any key to exit...${R}"
    read -k 1 -r -s
  fi
  ;;
w)
  wget -P ~/storage/downloads/Wget $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finished
    echo "${LG}Done.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Error
    echo "${LR}Error.${R}"
    echo ""
    echo "${W}Press any key to exit...${R}"
    read -k 1 -r -s
  fi
  ;;
a)
  aria2c -d ~/storage/downloads/Aria2 $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finished
    echo "${LG}Done.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Error
    echo "${LR}Error.${R}"
    echo ""
    echo "${W}Press any key to exit...${R}"
    read -k 1 -r -s
  fi
  ;;
n)
  megadl --path=storage/downloads/Mega/ $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finished
    echo "${LG}Done.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Error
    echo "${LR}Error.${R}"
    echo ""
    echo "${W}Press any key to exit...${R}"
    read -k 1 -r -s
  fi
  ;;
g)
  echo "${LG}Enter repository name:${R}"
  read REPO
  git clone $target "storage/downloads/Git/$REPO"
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finished
    echo "${LG}Done.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Error
    echo "${LR}Error.${R}"
    echo ""
    echo "${W}Press any key to exit...${R}"
    read -k 1 -r -s
  fi
  ;;
p)
  wget --mirror --page-requisites --html-extension --convert-links -P ~/storage/downloads/Websites $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finished
    echo "${LG}Done.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Error
    echo "${LR}Error.${R}"
    echo ""
    echo "${W}Press any key to exit...${R}"
    read -k 1 -r -s
  fi
  ;;
x)
  echo "${LG}Goodbye ;)${R}"
  sleep 2s
  ;;
esac
