#!/data/data/com.termux/files/usr/bin/zsh

#variables
target=$1

#colors
DG='\e[1;30m' # dark grey
LR='\e[1;31m' # light red
LG='\e[1;32m' # light green
LY='\e[1;33m' # light yellow
LB='\e[1;34m' # light blue
W='\e[1;37m'  # white
R='\e[0m'     # reset color / no color

echo "${DG}Analisando URL..."
echo "[${LB}$target${DG}]"
echo ""
echo "${LG}O que devo fazer?"
echo ""
echo "${LY}v${W}) Baixar vídeo"
echo "${LY}s${W}) Baixar vídeo (Selecionar formato)"
echo "${LY}m${W}) Baixar música"
echo "${LY}i${W}) Baixar imagem"
echo "${LY}w${W}) Baixar com wget"
echo "${LY}a${W}) Baixar com aria2"
echo "${LY}n${W}) Baixar com megatools"
echo "${LY}g${W}) Clonar git"
echo "${LY}p${W}) Clonar website"
echo "${LY}x${W}) ${LR}Sair${R}"

read CHOICE
case $CHOICE in
v)
  yt-dlp -n -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b" --embed-thumbnail --no-mtime -o "/storage/emulated/0/Movies/%(title)s.%(ext)s" $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finalizado
    echo "${LG}Feito.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Erro
    echo "${LR}Erro.${R}"
    echo ""
    echo "${W}Pressione qualquer tecla para sair...${R}"
    read -k 1 -r -s
  fi
  ;;
s)
  yt-dlp -F $target
  echo "${LG}Selecione o formato:${R}"
  read FORMAT
  yt-dlp -n -f $FORMAT --embed-thumbnail --no-mtime -o "/storage/emulated/0/Movies/%(title)s.%(ext)s" $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finalizado
    echo "${LG}Feito.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Erro
    echo "${LR}Erro.${R}"
    echo ""
    echo "${W}Pressione qualquer tecla para sair...${R}"
    read -k 1 -r -s
  fi
  ;;
m)
  yt-dlp -n -x --audio-format mp3 --audio-quality 0 --embed-thumbnail --convert-thumbnail jpg --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" --exec ffprobe --add-metadata --no-mtime -o "/storage/emulated/0/Music/%(artist,uploader)s - %(title)s.%(ext)s" $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finalizado
    echo "${LG}Feito.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Erro
    echo "${LR}Erro.${R}"
    echo ""
    echo "${W}Pressione qualquer tecla para sair...${R}"
    read -k 1 -r -s
  fi
  ;;
i)
  gallery-dl --netrc --no-mtime -f '{filename}.{extension}' -d "/storage/emulated/0/Pictures/GalleryDL" $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finalizado
    echo "${LG}Feito.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Erro
    echo "${LR}Erro.${R}"
    echo ""
    echo "${W}Pressione qualquer tecla para sair...${R}"
    read -k 1 -r -s
  fi
  ;;
w)
  wget -P ~/storage/downloads/Wget $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finalizado
    echo "${LG}Feito.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Erro
    echo "${LR}Erro.${R}"
    echo ""
    echo "${W}Pressione qualquer tecla para sair...${R}"
    read -k 1 -r -s
  fi
  ;;
a)
  aria2c -d ~/storage/downloads/Aria2 $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finalizado
    echo "${LG}Feito.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Erro
    echo "${LR}Erro.${R}"
    echo ""
    echo "${W}Pressione qualquer tecla para sair...${R}"
    read -k 1 -r -s
  fi
  ;;
n)
  megadl --path=storage/downloads/Mega/ $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finalizado
    echo "${LG}Feito.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Erro
    echo "${LR}Erro.${R}"
    echo ""
    echo "${W}Pressione qualquer tecla para sair...${R}"
    read -k 1 -r -s
  fi
  ;;
g)
  echo "${LG}Informe o nome do repositório:${R}"
  read REPO
  git clone $target "storage/downloads/Git/$REPO"
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finalizado
    echo "${LG}Feito.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Erro
    echo "${LR}Erro.${R}"
    echo ""
    echo "${W}Pressione qualquer tecla para sair...${R}"
    read -k 1 -r -s
  fi
  ;;
p)
  wget --mirror --page-requisites --html-extension --convert-links -P ~/storage/downloads/Websites $target
  if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c black Download finalizado
    echo "${LG}Feito.${R}"
    sleep 3s
  else
    termux-toast -g top -b white -c red Erro
    echo "${LR}Erro.${R}"
    echo ""
    echo "${W}Pressione qualquer tecla para sair...${R}"
    read -k 1 -r -s
  fi
  ;;
x)
  echo "${LG}Adeus ;)${R}"
  sleep 2s
  ;;
esac
