#!/bin/zsh
termux-wake-lock

tmux kill-session -t rcscrts
if [ $? -eq 0 ]; then
    termux-toast -g top -b white -c red Scrts FTP off
    termux-notification-remove scrts
  else
    termux-notification -t "Scrts FTP Server online" --button1 "Turn off" --button1-action ". ~/.shortcuts/tasks/switch-scrts" --ongoing --id scrts
    termux-toast -g top -b white -c black Scrts FTP on
    tmux new-session -d -s rcscrts
    tmux send-keys -t rcscrts 'rclone serve ftp --addr localhost:2122 --user admin --pass 123admin -L Scrts:' C-m
fi

# current terminal variable
tty=$(tty | tr -d /dev/)

# check if other terminals are running
# if not, release wake lock
ps -h | grep -v "$tty"
if [ $? -eq 0 ]; then
    sleep 0s
  else
    termux-wake-unlock
fi
